name: Unit Test & Docker image for application

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Build and push the image
        run: |
          docker login --username dap3884 --password ${{secrets.ACCESS_SECRET}} ghcr.io
          docker build -t ghcr.io/dap3884/bugtracker:latest --file Dockerfile .  
          docker push ghcr.io/dap3884/bugtracker:latest